### ISSUE TITLE
Publicly accessible logs.

### ISSUE THREAD

**Issue by lenlorijn** [firegento/magento1-shop#2]
Hey,

`var/log/exception.log` and `var/log/system.log` are publicly accessible.
I would consider this an information disclosure bug.
The .htaccess is not committed so I can't make a pull request for it.

`.gitignore` and `.git/config` are also accessible, but since this repository is public I guess it's not a real issue.

**Comment by mautz-et-tong** [comment]
Oh, I forgot to close this issue long time ago^^
Problems solved, thank.
